server:
    port: 8080
    context-path: /chaos    
    
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/chaos?useUnicode=true&characterEncoding=UTF-8
      username: duduba
      password: duduaiwo
#      schema: import.sql
# 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:      
    encoding.charset: UTF-8  
    encoding.enable: true  
    encoding.force: true        
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
  devtools:
    restart.exclude: static/**,public/**  # 只有static目录和public目录下的内容修改后不会引起重启

multipart:
  maxFileSize: 3Mb  # Set the file size limit (default 1Mb). If you want to specify that files be unlimited set the multipart.maxFileSize property to -1.
  maxRequestSize: 10Mb  # Set the total request size for a multipart/form-data (default 10Mb)
  
chaos:
  paths.uploadedFiles: /tmp/upload 
  